logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: island
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.210.203/island?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0

server:
  port: 8082
  servlet:
    session:
      cookie:
        max-age: -1